version: '3.4'

services:
  streammaster:
    image: senexcrenshaw/streammaster:0.1.0-alpha.582
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 7095:80
      - 7096:443
    environment:
      - STREAMMASTER_BASEHOSTURL=http://localhost:7095
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.streammaster:/root/.streammaster
      - ~/.streammaster/tv-logos:/root/.streammaster/tv-logos
      - ~/.streammaster/https:/https # put pfx here
