site_name: Stream Master
repo_url: https://github.com/SenexCrenshaw/StreamMaster
theme:
  name: "material"
  logo: "assets/sm_logo.png"
  features:
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - Getting Started ğŸš€: GettingStarted.md
  - Auth ğŸ”‘: Auth.md
  - EPG/XML Files ğŸ“…: EPG.md
  - M3U Files ğŸ“œ: M3U.md
  - Schedules Direct ğŸ“…: SD.md
  - StreamGroup ğŸ“º: StreamGroup.md
  - Profiles ğŸ§‘â€ğŸ’»:
      - CommandProfiles.md
      - OutputProfiles.md
  - Settings âš™ï¸: Settings.md
  - Docs ğŸ“˜: Docs.md
  - M3U Output AttributesğŸ¬: M3U_Output_Attributes.md
    # - M3UGroupTitle.md
  - Contributors ğŸŒŸ: Contributors.md

plugins:
  - search
  - include-markdown
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        # - locale: es
        #   name: Spanish
        #   build: true
        # - locale: fr
        #   name: French
        #   build: true
        # - locale: de
        #   name: German
        #   build: true
        # - locale: pt
        #   name: Portuguese
        #   build: true
        # - locale: da
        #   name: Danish
        #   build: true
        # - locale: sv
        #   name: Swedish
        #   build: true
        # - locale: nb
        #   name: Norwegian BokmÃ¥l
        #   build: true
        # - locale: fi
        #   name: Finnish
        #   build: true
        # - locale: is
        #   name: Icelandic
        #   build: true
site_url: "https://senexcrenshaw.github.io/StreamMaster/"
